### ISSUE TITLE
Optimize CI and CD pipelines: Merge into one CICD pipeline

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/website-sommerfeld-io#18]
As a DevOps engineer I want to continuously test and publish my complete website. The website should be up to date with minimal to no manual effort (other than writing content). I want to deploy only when new all checks and tests have passed.

#### Current implementation
I already have a CI pipeline to continuously validate / lint / test my website. And I already have a CD pipeline which continuously deploys the latest state to production. But these pipelines don't build on each other. It is possible for CI to fail but still have CD upate my website which is not the desired state.

### Acceptance Criteria
- [x] There is only one CICD pipeline, not multiple pipelines running separately (any at the same time).
- [x] CI Tasks run for all branches
- [x] CI Tasks run for tags as well (because CD builds on these tasks)
- [x] CD tasks only run when all CI steps pass. 
- [x] CD tasks run for branch `main`, not for other branches.
- [x] CD tasks run for new tags
- [x] There is no dedicated Release pipeline. All tasks from Release are part of CD now.

Once website-sommerfeld-io works with the new CICD pipeline, adopt this pipeline for all other website projects as well
- [x] sebastian-sommerfeld-io/website-numero-uno-de#8
- [x] sebastian-sommerfeld-io/website-masterblender-de#9
- [x] sebastian-sommerfeld-io/website-tafelboy-de#7

Once website-sommerfeld-io works with the new CICD pipeline, adopt this pipeline style (one CICD pipeline instead of CI, CI and Release) for all other docker images as well
- [x] sebastian-sommerfeld-io/docker-image-adoc-antora#26
- [x] sebastian-sommerfeld-io/docker-image-ftp-client#9
- [x] sebastian-sommerfeld-io/docker-image-jq#10
- [x] sebastian-sommerfeld-io/docker-image-git#10
- [x] sebastian-sommerfeld-io/docker-image-terraform#5
- [x] sebastian-sommerfeld-io/docker-image-folderslint#14

Follow-up adjustments
- [x] github-action-generate-docs must use `sommerfeldio/git:ci` instead of `sommerfeldio/git:ci-build`

**Comment by sebastian-sommerfeld-io** [comment]
### Questions / Open decisions
- What about the generate-docs pipeline? Should be the first step or one of the first steps, before deploying the website. Otherwise maybe the latest docs are not deployed. But do I want to put everything in one pipeline? Plus all other non-website repos would still keep this pipeline. Then the website projects would not follow the same pattern.
    - **Answer:** Leave the generate-docs pipeline separate for the moment. This only might result in problems when the content in the website-sommerfeld-io repo is changed. Most changes happen in the respective project-repo anyway and don't affect this repo.
