### ISSUE TITLE
Review Snyk Steps in Pipelines

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/website-sommerfeld-io#27]
As a DevOps engineer I want to regularly scan my latest published docker image for security issues. I only want to scan the latest image because ...

1. Github only provides one view for security issues and scanning multiple image tags would result in overriding the existing findings all the time
2. Want to encourage use of the latest image

### Acceptance criteria
- [x] There is a dedicated security scan pipeline
- [x] Security scans run regularly
- [x] Security Scans are not part of CICD pipeline
- [x] sebastian-sommerfeld-io/configs#61
- [x] sebastian-sommerfeld-io/docker-image-adoc-antora#27
- [x] sebastian-sommerfeld-io/website-masterblender-de#10
- [x] sebastian-sommerfeld-io/github-action-generate-readme#11
- [x] sebastian-sommerfeld-io/github-action-update-antora-yml#13
- [x] sebastian-sommerfeld-io/docker-image-ftp-client#10
- [x] sebastian-sommerfeld-io/docker-image-jq#11
- [x] sebastian-sommerfeld-io/docker-image-git#11
- [x] sebastian-sommerfeld-io/docker-image-terraform#6
- [x] sebastian-sommerfeld-io/github-action-generate-docs#10
- [x] sebastian-sommerfeld-io/website-numero-uno-de#9
- [x] sebastian-sommerfeld-io/docker-image-folderslint#15
- [x] sebastian-sommerfeld-io/jarvis#68
- [x] sebastian-sommerfeld-io/website-tafelboy-de#8
